spring:
  datasource:
    url: jdbc:mysql://47.105.144.209:3306/recycle?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: wxx
    password: tangseng726
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.frame.fast
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
  mapper-locations: classpath:mapper/*Mapper.xml


server:
  port: 8080

appSecret: 1a41ec237afa26eb4738d45ef4b33a6e
logging:
  config: classpath:logback.xml
