spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recycle?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.frame.fast
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
  mapper-locations: classpath:mapper/*Mapper.xml


server:
  port: 8080

logging:
  config: classpath:logback.xml
