spring:
  datasource:
    url: jdbc:mysql://47.105.144.209:3306/recycle?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: wxx
    password: tangseng726
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 47.105.144.209
    port: 6897
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
mybatis-plus:
  type-aliases-package: com.frame.fast
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
  mapper-locations: classpath:mapper/*Mapper.xml
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.frame.fast.model

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
#  path: E:/logs/fast
  path: /home/log

appId: wxbc1b80f39e9ef6a8