spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recycle?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=CTT
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.1.1
    port: 6897
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  mail:
    host: smtp.163.com
    username: example@163.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  type-aliases-package: com.frame.fast
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
  mapper-locations: classpath:mapper/*Mapper.xml
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.frame.fast.model

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
#  path: E:/logs/fast
  path: /home/log

appId: anappid

mail:
  fromMail:
    addr: demo@163.com


management:
  endpoints:
    web:
      exposure:
        include: "*"
